# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: contrib
name: summit
version: 0.1.0
readme: README.md
authors:
  - Sviatoslav Sydorenko (github.com/webknjaz)
description: Ansible Contributor Summit 2022.10 demo
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - contrib
  - summit
  - demo
repository: https://github.com/webknjaz/ansible-collection-demo-2022-10.contrib.summit
#documentation: https://github.com/webknjaz/ansible-collection-demo-2022-10.contrib.summit/tree/main/docs
homepage: https://github.com/webknjaz/ansible-collection-demo-2022-10.contrib.summit
issues: https://github.com/webknjaz/ansible-collection-demo-2022-10.contrib.summit/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
